### ISSUE TITLE
1.4.1: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [aio-libs/frozenlist#570]
## Long story short
Looks like with 1.4.1 documentation build fails

## Expected behaviour
Documentation should build correctly.

## Actual behaviour
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.1.2
Initializing Spelling Checker 8.0.0
making output directory... done
loading intersphinx inventory from http://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.aiohttp.org/en/stable/objects.inv...
intersphinx inventory has moved: http://docs.python.org/3/objects.inv -> https://docs.python.org/3/objects.inv
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 363, in get_outdated_docs
    towncrier_fragment_paths = _lookup_towncrier_fragments(
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/towncrier/ext.py", line 132, in _lookup_towncrier_fragments
    fragment_base_directory = project_path / towncrier_config['directory']
TypeError: 'Config' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 290, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 287, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 381, in read
    for docs in self.events.emit('env-get-outdated', self.env, added, changed, removed):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7f053a59bb50>> for event 'env-get-outdated' threw an exception (exception: 'Config' object is not subscriptable)

Extension error (sphinxcontrib.towncrier.ext):
Handler <bound method TowncrierDraftEntriesEnvironmentCollector.get_outdated_docs of <sphinxcontrib.towncrier.ext.TowncrierDraftEntriesEnvironmentCollector object at 0x7f053a59bb50>> for event 'env-get-outdated' threw an exception (exception: 'Config' object is not subscriptable)
```

## Steps to reproduce
just run `sphinx-build -n -T -b man docs`

## Your environment
<details>
<summary>List of installed modules in build env:</summary>

```console
Package                       Version
----------------------------- -------
alabaster                     0.7.13
Babel                         2.14.0
build                         1.0.3
charset-normalizer            3.3.2
click                         8.1.7
cppclean                      0.13
Cython                        3.0.6
distro                        1.8.0
dnf                           4.18.1
docutils                      0.20.1
exceptiongroup                1.1.3
expandvars                    0.12.0
gpg                           1.23.2
idna                          3.6
imagesize                     1.4.1
importlib-metadata            7.0.0
importlib-resources           6.1.1
incremental                   22.10.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.2
libdnf                        0.72.0
MarkupSafe                    2.1.3
packaging                     23.2
pluggy                        1.3.0
Pygments                      2.17.2
pyproject_hooks               1.0.0
pytest                        7.4.3
python-dateutil               2.8.2
pytz                          2023.3
requests                      2.31.0
setuptools                    69.0.2
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        7.1.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.5
sphinxcontrib-htmlhelp        2.0.4
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.9
sphinxcontrib-towncrier       0.3.1a3
tomli                         2.0.1
towncrier                     23.11.0
urllib3                       1.26.18
wheel                         0.42.0
zipp                          3.17.0
```
</details>

**Comment by webknjaz** [comment]
We don't build manpages. If you make a pull request, I might be able to review. Otherwise, its not something of concern.
